name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get versions
      id: version
      run: |
        echo "::set-output name=full::$(awk -F, '{print $1}' .tags)"
    - name: Docker Setup qemu-action
      uses: docker/setup-qemu-action@v1
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1
    - name: DockerHub Login
      uses: docker/login-action@v1.6.0
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: CNB Login
      uses: docker/login-action@v1.6.0
      with:
        registry: docker.cnb.cool
        username: cnb
        password: ${{ secrets.CNB_TOKEN }}

    - name: Build nginx Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: |
          vanjoge/nginx-rtmp:flvlive
          docker.cnb.cool/rtvsmirror/vanjoge/nginx-rtmp:flvlive

